#!/bin/bash
# Reads each .scm file from Resources/queries/ and generates a Swift file
# with static [UInt8] arrays for each query. Run this when adding a language.
#
# Usage: ./scripts/generate-embedded-queries.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
QUERIES_DIR="$SCRIPT_DIR/../Sources/dog/Resources/queries"
OUTPUT="$SCRIPT_DIR/../Sources/dog/Parsing/Languages/EmbeddedQueries.swift"

cat > "$OUTPUT" << 'HEADER'
// Auto-generated by scripts/generate-embedded-queries.sh
// Do not edit manually. Rerun the script when adding or updating queries.

enum EmbeddedQueries {
HEADER

for scm in "$QUERIES_DIR"/*.scm; do
  name=$(basename "$scm" .scm)

  # Convert name to a valid Swift identifier (e.g. markdown_inline stays as-is)
  swift_name="$name"

  # Generate the [UInt8] literal from file bytes
  printf "  static let %s: [UInt8] = [\n    " "$swift_name" >> "$OUTPUT"

  # Use xxd to dump bytes, format as Swift UInt8 array
  xxd -i < "$scm" | tr -d '\n' | sed 's/  */ /g' | fold -s -w 80 | sed 's/^/    /' >> "$OUTPUT"

  printf "\n  ]\n\n" >> "$OUTPUT"
done

echo "}" >> "$OUTPUT"

echo "Generated $(wc -l < "$OUTPUT" | tr -d ' ') lines → $OUTPUT"
