#!/bin/bash
# Reads each .txt file from Resources/woof/ and generates a Swift file
# with static [UInt8] arrays for each snippet. Run this when adding or
# updating woof preview snippets.
#
# Filename convention: <language>.txt where language matches LanguageRegistry
# (e.g. swift.txt, typescript.txt, rust.txt).
#
# Usage: ./scripts/generate-woof-snippets.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WOOF_DIR="$SCRIPT_DIR/../Sources/dog/Resources/woof"
OUTPUT="$SCRIPT_DIR/../Sources/dog/Theme/EmbeddedWoofSnippets.swift"

if [ ! -d "$WOOF_DIR" ]; then
  echo "Error: $WOOF_DIR does not exist"
  exit 1
fi

cat > "$OUTPUT" << 'HEADER'
// Auto-generated by scripts/generate-woof-snippets.sh
// Do not edit manually. Rerun the script when adding or updating snippets.
//
// Each static let is a [UInt8] containing the raw UTF-8 bytes of a dog-themed
// code snippet for the --woof theme previewer. Language name matches the
// LanguageRegistry key (e.g. `swift`, `rust`, `python`).

enum EmbeddedWoofSnippets {
HEADER

count=0
for txt in "$WOOF_DIR"/*.txt; do
  [ -f "$txt" ] || continue
  name=$(basename "$txt" .txt)

  printf "  static let %s: [UInt8] = [\n    " "$name" >> "$OUTPUT"

  xxd -i < "$txt" | tr -d '\n' | sed 's/  */ /g' | fold -s -w 80 | sed 's/^/    /' >> "$OUTPUT"

  printf "\n  ]\n\n" >> "$OUTPUT"
  count=$((count + 1))
done

# Add a lookup table so the woof command can iterate all snippets
printf "  /// All embedded snippets as (language, bytes) pairs.\n" >> "$OUTPUT"
printf "  static let all: [(language: String, bytes: [UInt8])] = [\n" >> "$OUTPUT"

for txt in "$WOOF_DIR"/*.txt; do
  [ -f "$txt" ] || continue
  name=$(basename "$txt" .txt)
  printf "    (\"%s\", %s),\n" "$name" "$name" >> "$OUTPUT"
done

printf "  ]\n" >> "$OUTPUT"
echo "}" >> "$OUTPUT"

echo "Generated $count snippets ($(wc -l < "$OUTPUT" | tr -d ' ') lines) → $OUTPUT"
