#!/bin/bash
# Regenerate Sources/dog/Parsing/Languages/EmbeddedCompiledQueries.swift —
# build-time precompiled highlight queries (perf Item 4 / experiment 003b).
#
# Pipeline, per language: build gen-query-blob against the PATCHED vendored
# runtime (LocalPackages/tree-sitter) + that grammar's parser -> compile the
# .scm once -> serialize -> self-check round trip -> blob file. Then all blobs
# are wrapped into one generated Swift file (committed to the repo, so normal
# builds are single-stage).
#
# Run after ANY change to: a query in Sources/dog/Resources/queries/, a grammar,
# or the vendored runtime. Stale blobs are SAFE but slow — the loader verifies
# a query-source hash and falls back to ts_query_new with a stderr warning.
#
#   bash scripts/generate/query-blobs.sh
#
# Requires: .build/checkouts populated (swift package resolve) for the four
# remote grammars (bash, go, swift, markdown).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TS="$PROJECT_ROOT/LocalPackages/tree-sitter"
QUERIES="$PROJECT_ROOT/Sources/dog/Resources/queries"
OUTPUT_SWIFT="$PROJECT_ROOT/Sources/dog/Parsing/Languages/EmbeddedCompiledQueries.swift"
WORK_DIR=$(mktemp -d)
trap 'rm -rf "$WORK_DIR"' EXIT

swift_grammar_src="$(dirname "$(find "$PROJECT_ROOT/.build/checkouts/tree-sitter-swift" -name parser.c -not -path '*/node_modules/*' | head -1)")"
markdown_grammar_src="$(dirname "$(find "$PROJECT_ROOT/.build/checkouts"/tree-sitter-markdown* -path '*tree-sitter-markdown/src/parser.c' -not -path '*inline*' | head -1)")"

# language  LANG_FN  grammar-src-dir
LANGUAGES=(
  "bash tree_sitter_bash $PROJECT_ROOT/.build/checkouts/tree-sitter-bash/src"
  "c tree_sitter_c $PROJECT_ROOT/LocalPackages/tree-sitter-c/src"
  "cpp tree_sitter_cpp $PROJECT_ROOT/LocalPackages/tree-sitter-cpp/src"
  "css tree_sitter_css $PROJECT_ROOT/LocalPackages/tree-sitter-css/src"
  "go tree_sitter_go $PROJECT_ROOT/.build/checkouts/tree-sitter-go/src"
  "html tree_sitter_html $PROJECT_ROOT/LocalPackages/tree-sitter-html/src"
  "javascript tree_sitter_javascript $PROJECT_ROOT/LocalPackages/tree-sitter-javascript/src"
  "json tree_sitter_json $PROJECT_ROOT/LocalPackages/tree-sitter-json/src"
  "lua tree_sitter_lua $PROJECT_ROOT/LocalPackages/tree-sitter-lua/src"
  "markdown tree_sitter_markdown $markdown_grammar_src"
  "python tree_sitter_python $PROJECT_ROOT/LocalPackages/tree-sitter-python/src"
  "ruby tree_sitter_ruby $PROJECT_ROOT/LocalPackages/tree-sitter-ruby/src"
  "rust tree_sitter_rust $PROJECT_ROOT/LocalPackages/tree-sitter-rust/src"
  "swift tree_sitter_swift $swift_grammar_src"
  "tsx tree_sitter_tsx $PROJECT_ROOT/LocalPackages/tree-sitter-typescript/tsx/src"
  "typescript tree_sitter_typescript $PROJECT_ROOT/LocalPackages/tree-sitter-typescript/typescript/src"
  "yaml tree_sitter_yaml $PROJECT_ROOT/LocalPackages/tree-sitter-yaml/src"
)

for entry in "${LANGUAGES[@]}"; do
  read -r language language_fn grammar_src <<< "$entry"
  [[ -d "$grammar_src" ]] || { echo "missing grammar src for $language: $grammar_src" >&2; exit 1; }
  scanner_arg=""
  [[ -f "$grammar_src/scanner.c" ]] && scanner_arg="$grammar_src/scanner.c"

  cc -O2 -DLANG_FN="$language_fn" -o "$WORK_DIR/gen-$language" \
    "$SCRIPT_DIR/gen-query-blob.c" \
    "$TS/lib/src/lib.c" -I"$TS/lib/include" -I"$TS/lib/src" \
    "$grammar_src/parser.c" $scanner_arg -I"$grammar_src"
  "$WORK_DIR/gen-$language" "$QUERIES/$language.scm" "$WORK_DIR/$language.blob"
done

uv run python3 - "$WORK_DIR" "$OUTPUT_SWIFT" <<'PYEOF'
import sys
from pathlib import Path

work_dir, output_path = Path(sys.argv[1]), Path(sys.argv[2])
lines = [
    "// Generated by scripts/generate/query-blobs.sh — DO NOT EDIT.",
    "//",
    "// Precompiled highlight-query blobs (ts_query_serialize output). Loaded",
    "// via ts_query_deserialize, which validates magic/format/struct sizes/",
    "// grammar ABI/query hash and returns nil on any mismatch — stale blobs",
    "// fall back to ts_query_new (slower, never wrong). Regenerate after any",
    "// query, grammar, or vendored-runtime change.",
    "",
    "enum EmbeddedCompiledQueries {",
]
for blob_path in sorted(work_dir.glob("*.blob")):
    language = blob_path.stem
    data = blob_path.read_bytes()
    lines.append(f"  static let {language}: [UInt8] = [")
    for row_start in range(0, len(data), 20):
        row = ", ".join(str(byte) for byte in data[row_start:row_start + 20])
        lines.append(f"    {row},")
    lines.append("  ]")
    lines.append("")
lines.append("}")
output_path.write_text("\n".join(lines) + "\n")
total = sum(path.stat().st_size for path in work_dir.glob("*.blob"))
print(f"{output_path}: {len(list(work_dir.glob('*.blob')))} blobs, {total} raw bytes")
PYEOF
